//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TDImporterXML.RobotPosService.RobotposServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="integrationServiceSoap", Namespace="http://integration.infinia.robotpos.com/")]
    public partial class integrationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getXmlDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback addZreportOperationCompleted;
        
        private System.Threading.SendOrPostCallback addZreportErrorOperationCompleted;
        
        private System.Threading.SendOrPostCallback getZreportJobOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkZreportJobOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLastZOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public integrationService() {
            this.Url = global::TDImporterXML.RobotPosService.Properties.Settings.Default.TDImporterXML_RobotPosService_RobotposServices_integrationService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getXmlDataCompletedEventHandler getXmlDataCompleted;
        
        /// <remarks/>
        public event addZreportCompletedEventHandler addZreportCompleted;
        
        /// <remarks/>
        public event addZreportErrorCompletedEventHandler addZreportErrorCompleted;
        
        /// <remarks/>
        public event getZreportJobCompletedEventHandler getZreportJobCompleted;
        
        /// <remarks/>
        public event checkZreportJobCompletedEventHandler checkZreportJobCompleted;
        
        /// <remarks/>
        public event getLastZCompletedEventHandler getLastZCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://integration.infinia.robotpos.com/getXmlData", RequestNamespace="http://integration.infinia.robotpos.com/", ResponseNamespace="http://integration.infinia.robotpos.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getXmlData(string securityKey, int dataTypeID, string appName, string branchList, string startDate, string endDate, string sendAll) {
            object[] results = this.Invoke("getXmlData", new object[] {
                        securityKey,
                        dataTypeID,
                        appName,
                        branchList,
                        startDate,
                        endDate,
                        sendAll});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getXmlDataAsync(string securityKey, int dataTypeID, string appName, string branchList, string startDate, string endDate, string sendAll) {
            this.getXmlDataAsync(securityKey, dataTypeID, appName, branchList, startDate, endDate, sendAll, null);
        }
        
        /// <remarks/>
        public void getXmlDataAsync(string securityKey, int dataTypeID, string appName, string branchList, string startDate, string endDate, string sendAll, object userState) {
            if ((this.getXmlDataOperationCompleted == null)) {
                this.getXmlDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetXmlDataOperationCompleted);
            }
            this.InvokeAsync("getXmlData", new object[] {
                        securityKey,
                        dataTypeID,
                        appName,
                        branchList,
                        startDate,
                        endDate,
                        sendAll}, this.getXmlDataOperationCompleted, userState);
        }
        
        private void OngetXmlDataOperationCompleted(object arg) {
            if ((this.getXmlDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getXmlDataCompleted(this, new getXmlDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://integration.infinia.robotpos.com/addZreport", RequestNamespace="http://integration.infinia.robotpos.com/", ResponseNamespace="http://integration.infinia.robotpos.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AddZReportReturnModel addZreport(string securityKey, int branchId, string stationEcrNo, string jsonData) {
            object[] results = this.Invoke("addZreport", new object[] {
                        securityKey,
                        branchId,
                        stationEcrNo,
                        jsonData});
            return ((AddZReportReturnModel)(results[0]));
        }
        
        /// <remarks/>
        public void addZreportAsync(string securityKey, int branchId, string stationEcrNo, string jsonData) {
            this.addZreportAsync(securityKey, branchId, stationEcrNo, jsonData, null);
        }
        
        /// <remarks/>
        public void addZreportAsync(string securityKey, int branchId, string stationEcrNo, string jsonData, object userState) {
            if ((this.addZreportOperationCompleted == null)) {
                this.addZreportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddZreportOperationCompleted);
            }
            this.InvokeAsync("addZreport", new object[] {
                        securityKey,
                        branchId,
                        stationEcrNo,
                        jsonData}, this.addZreportOperationCompleted, userState);
        }
        
        private void OnaddZreportOperationCompleted(object arg) {
            if ((this.addZreportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addZreportCompleted(this, new addZreportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://integration.infinia.robotpos.com/addZreportError", RequestNamespace="http://integration.infinia.robotpos.com/", ResponseNamespace="http://integration.infinia.robotpos.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool addZreportError(string securityKey, System.DateTime addDateTime, string stationEcrNo, int branchId, string message) {
            object[] results = this.Invoke("addZreportError", new object[] {
                        securityKey,
                        addDateTime,
                        stationEcrNo,
                        branchId,
                        message});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void addZreportErrorAsync(string securityKey, System.DateTime addDateTime, string stationEcrNo, int branchId, string message) {
            this.addZreportErrorAsync(securityKey, addDateTime, stationEcrNo, branchId, message, null);
        }
        
        /// <remarks/>
        public void addZreportErrorAsync(string securityKey, System.DateTime addDateTime, string stationEcrNo, int branchId, string message, object userState) {
            if ((this.addZreportErrorOperationCompleted == null)) {
                this.addZreportErrorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddZreportErrorOperationCompleted);
            }
            this.InvokeAsync("addZreportError", new object[] {
                        securityKey,
                        addDateTime,
                        stationEcrNo,
                        branchId,
                        message}, this.addZreportErrorOperationCompleted, userState);
        }
        
        private void OnaddZreportErrorOperationCompleted(object arg) {
            if ((this.addZreportErrorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addZreportErrorCompleted(this, new addZreportErrorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://integration.infinia.robotpos.com/getZreportJob", RequestNamespace="http://integration.infinia.robotpos.com/", ResponseNamespace="http://integration.infinia.robotpos.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int getZreportJob(string securityKey, string stationEcrNo) {
            object[] results = this.Invoke("getZreportJob", new object[] {
                        securityKey,
                        stationEcrNo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void getZreportJobAsync(string securityKey, string stationEcrNo) {
            this.getZreportJobAsync(securityKey, stationEcrNo, null);
        }
        
        /// <remarks/>
        public void getZreportJobAsync(string securityKey, string stationEcrNo, object userState) {
            if ((this.getZreportJobOperationCompleted == null)) {
                this.getZreportJobOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetZreportJobOperationCompleted);
            }
            this.InvokeAsync("getZreportJob", new object[] {
                        securityKey,
                        stationEcrNo}, this.getZreportJobOperationCompleted, userState);
        }
        
        private void OngetZreportJobOperationCompleted(object arg) {
            if ((this.getZreportJobCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getZreportJobCompleted(this, new getZreportJobCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://integration.infinia.robotpos.com/checkZreportJob", RequestNamespace="http://integration.infinia.robotpos.com/", ResponseNamespace="http://integration.infinia.robotpos.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool checkZreportJob(string securityKey, string stationEcrNo) {
            object[] results = this.Invoke("checkZreportJob", new object[] {
                        securityKey,
                        stationEcrNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void checkZreportJobAsync(string securityKey, string stationEcrNo) {
            this.checkZreportJobAsync(securityKey, stationEcrNo, null);
        }
        
        /// <remarks/>
        public void checkZreportJobAsync(string securityKey, string stationEcrNo, object userState) {
            if ((this.checkZreportJobOperationCompleted == null)) {
                this.checkZreportJobOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckZreportJobOperationCompleted);
            }
            this.InvokeAsync("checkZreportJob", new object[] {
                        securityKey,
                        stationEcrNo}, this.checkZreportJobOperationCompleted, userState);
        }
        
        private void OncheckZreportJobOperationCompleted(object arg) {
            if ((this.checkZreportJobCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkZreportJobCompleted(this, new checkZreportJobCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://integration.infinia.robotpos.com/getLastZ", RequestNamespace="http://integration.infinia.robotpos.com/", ResponseNamespace="http://integration.infinia.robotpos.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int getLastZ(string securityKey, string stationEcrNo, int branchID) {
            object[] results = this.Invoke("getLastZ", new object[] {
                        securityKey,
                        stationEcrNo,
                        branchID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void getLastZAsync(string securityKey, string stationEcrNo, int branchID) {
            this.getLastZAsync(securityKey, stationEcrNo, branchID, null);
        }
        
        /// <remarks/>
        public void getLastZAsync(string securityKey, string stationEcrNo, int branchID, object userState) {
            if ((this.getLastZOperationCompleted == null)) {
                this.getLastZOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLastZOperationCompleted);
            }
            this.InvokeAsync("getLastZ", new object[] {
                        securityKey,
                        stationEcrNo,
                        branchID}, this.getLastZOperationCompleted, userState);
        }
        
        private void OngetLastZOperationCompleted(object arg) {
            if ((this.getLastZCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLastZCompleted(this, new getLastZCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1649.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://integration.infinia.robotpos.com/")]
    public partial class AddZReportReturnModel {
        
        private bool statusField;
        
        private int waitingZField;
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int WaitingZ {
            get {
                return this.waitingZField;
            }
            set {
                this.waitingZField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void getXmlDataCompletedEventHandler(object sender, getXmlDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getXmlDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getXmlDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void addZreportCompletedEventHandler(object sender, addZreportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addZreportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addZreportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddZReportReturnModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddZReportReturnModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void addZreportErrorCompletedEventHandler(object sender, addZreportErrorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addZreportErrorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addZreportErrorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void getZreportJobCompletedEventHandler(object sender, getZreportJobCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getZreportJobCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getZreportJobCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void checkZreportJobCompletedEventHandler(object sender, checkZreportJobCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkZreportJobCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkZreportJobCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void getLastZCompletedEventHandler(object sender, getLastZCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLastZCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLastZCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591